### ISSUE TITLE
error

### ISSUE THREAD

**Issue by msikorski26** [LuckPerms/rest-api#6]
`Starting docker_luckperms-rest-api_1 ... done
Attaching to docker_luckperms-rest-api_1
luckperms-rest-api_1  | 2022-10-31 12:24:35,022 main WARN Advanced terminal features are not available in this environment
luckperms-rest-api_1  | [12:24:35 INFO]:         __
luckperms-rest-api_1  | [12:24:35 INFO]:   |    |__)   LuckPerms v5.4.52
luckperms-rest-api_1  | [12:24:35 INFO]:   |___ |      Running on Standalone - standalone
luckperms-rest-api_1  | [12:24:35 INFO]:
luckperms-rest-api_1  | [12:24:35 INFO]: Loading configuration...
luckperms-rest-api_1  | [12:24:35 INFO]: Resolved configuration value from environment variable: LUCKPERMS_DATA_ADDRESS = database:3306
luckperms-rest-api_1  | [12:24:35 INFO]: Resolved configuration value from environment variable: LUCKPERMS_DATA_DATABASE = ungmcraft_lp
luckperms-rest-api_1  | [12:24:35 INFO]: Resolved configuration value from environment variable: LUCKPERMS_DATA_USERNAME = ungmcraft_lp
luckperms-rest-api_1  | [12:24:35 INFO]: Resolved configuration value from environment variable: LUCKPERMS_DATA_PASSWORD = *****
luckperms-rest-api_1  | [12:24:35 INFO]: Resolved configuration value from environment variable: LUCKPERMS_STORAGE_METHOD = mysql
luckperms-rest-api_1  | [12:24:35 INFO]: Loading storage provider... [MYSQL]
luckperms-rest-api_1  | WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
luckperms-rest-api_1  | [12:24:35 INFO]: luckperms-hikari - Starting...
luckperms-rest-api_1  | [12:24:35 INFO]: luckperms-hikari - Start completed.
luckperms-rest-api_1  | [12:24:40 ERROR]: Failed to init storage implementation
luckperms-rest-api_1  | java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5000ms.
luckperms-rest-api_1  |         at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696) ~[?:?]
luckperms-rest-api_1  |         at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:197) ~[?:?]
luckperms-rest-api_1  |         at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:162) ~[?:?]
luckperms-rest-api_1  |         at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100) ~[?:?]
luckperms-rest-api_1  |         at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:174) ~[?:?]
luckperms-rest-api_1  |         at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.init(SqlStorage.java:169) ~[?:?]
luckperms-rest-api_1  |         at me.lucko.luckperms.common.storage.Storage.init(Storage.java:117) ~[?:?]
luckperms-rest-api_1  |         at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:88) ~[?:?]
luckperms-rest-api_1  |         at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:184) ~[?:?]
luckperms-rest-api_1  |         at me.lucko.luckperms.standalone.LPStandaloneBootstrap.onEnable(LPStandaloneBootstrap.java:109) ~[?:?]
luckperms-rest-api_1  |         at me.lucko.luckperms.standalone.loader.StandaloneLoader.start(StandaloneLoader.java:90) ~[luckperms-standalone.jar:?]
luckperms-rest-api_1  |         at me.lucko.luckperms.standalone.loader.StandaloneLoader.main(StandaloneLoader.java:66) ~[luckperms-standalone.jar:?]
luckperms-rest-api_1  | Caused by: java.sql.SQLException: Access denied for user 'ungmcraft_lp'@'172.19.0.2' (using password: YES)
luckperms-rest-api_1  |         at me.lucko.luckperms.lib.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[?:?]
luckperms-rest-api_1  |         at me.lucko.luckperms.lib.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[?:?]
luckperms-rest-api_1  |         at me.lucko.luckperms.lib.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:833) ~[?:?]
luckperms-rest-api_1  |         at me.lucko.luckperms.lib.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453) ~[?:?]
luckperms-rest-api_1  |         at me.lucko.luckperms.lib.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[?:?]
luckperms-rest-api_1  |         at me.lucko.luckperms.lib.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[?:?]
luckperms-rest-api_1  |         at me.lucko.luckperms.lib.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[?:?]
luckperms-rest-api_1  |         at me.lucko.luckperms.lib.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[?:?]
luckperms-rest-api_1  |         at me.lucko.luckperms.lib.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[?:?]
luckperms-rest-api_1  |         at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[?:?]
luckperms-rest-api_1  |         at me.lucko.luckperms.lib.hikari.pool.HikariPool.access$100(HikariPool.java:71) ~[?:?]
luckperms-rest-api_1  |         at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726) ~[?:?]
luckperms-rest-api_1  |         at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712) ~[?:?]
luckperms-rest-api_1  |         at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
luckperms-rest-api_1  |         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
luckperms-rest-api_1  |         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
luckperms-rest-api_1  |         at java.lang.Thread.run(Thread.java:833) ~[?:?]
luckperms-rest-api_1  | [12:24:40 INFO]: Loading messaging service... [SQL]
luckperms-rest-api_1  | [12:24:45 ERROR]: Exception occurred whilst enabling SQL messaging service
luckperms-rest-api_1  | java.lang.RuntimeException: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5000ms.
luckperms-rest-api_1  |         at me.lucko.luckperms.common.messaging.sql.SqlMessenger.init(SqlMessenger.java:57) ~[?:?]
luckperms-rest-api_1  |         at me.lucko.luckperms.common.messaging.MessagingFactory$SqlMessengerProvider.obtain(MessagingFactory.java:195) ~[?:?]
luckperms-rest-api_1  |         at me.lucko.luckperms.common.messaging.LuckPermsMessagingService.<init>(LuckPermsMessagingService.java:71) ~[?:?]
luckperms-rest-api_1  |         at me.lucko.luckperms.common.messaging.MessagingFactory.getServiceFor(MessagingFactory.java:121) ~[?:?]
luckperms-rest-api_1  |         at me.lucko.luckperms.standalone.StandaloneMessagingFactory.getServiceFor(StandaloneMessagingFactory.java:39) ~[?:?]
luckperms-rest-api_1  |         at me.lucko.luckperms.common.messaging.MessagingFactory.getInstance(MessagingFactory.java:89) ~[?:?]
luckperms-rest-api_1  |         at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:185) ~[?:?]
luckperms-rest-api_1  |         at me.lucko.luckperms.standalone.LPStandaloneBootstrap.onEnable(LPStandaloneBootstrap.java:109) ~[?:?]
luckperms-rest-api_1  |         at me.lucko.luckperms.standalone.loader.StandaloneLoader.start(StandaloneLoader.java:90) ~[luckperms-standalone.jar:?]
luckperms-rest-api_1  |         at me.lucko.luckperms.standalone.loader.StandaloneLoader.main(StandaloneLoader.java:66) ~[luckperms-standalone.jar:?]
luckperms-rest-api_1  | Caused by: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5000ms.
luckperms-rest-api_1  |         at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696) ~[?:?]
luckperms-rest-api_1  |         at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:197) ~[?:?]
luckperms-rest-api_1  |         at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:162) ~[?:?]
luckperms-rest-api_1  |         at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100) ~[?:?]
luckperms-rest-api_1  |         at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:174) ~[?:?]
luckperms-rest-api_1  |         at me.lucko.luckperms.common.messaging.sql.SqlMessenger.getConnection(SqlMessenger.java:85) ~[?:?]
luckperms-rest-api_1  |         at me.lucko.luckperms.common.messaging.sql.AbstractSqlMessenger.init(AbstractSqlMessenger.java:61) ~[?:?]
luckperms-rest-api_1  |         at me.lucko.luckperms.common.messaging.sql.SqlMessenger.init(SqlMessenger.java:55) ~[?:?]
luckperms-rest-api_1  |         ... 9 more
luckperms-rest-api_1  | Caused by: java.sql.SQLException: Access denied for user 'ungmcraft_lp'@'172.19.0.2' (using password: YES)
luckperms-rest-api_1  |         at me.lucko.luckperms.lib.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[?:?]
luckperms-rest-api_1  |         at me.lucko.luckperms.lib.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[?:?]
luckperms-rest-api_1  |         at me.lucko.luckperms.lib.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:833) ~[?:?]
luckperms-rest-api_1  |         at me.lucko.luckperms.lib.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453) ~[?:?]
luckperms-rest-api_1  |         at me.lucko.luckperms.lib.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[?:?]
luckperms-rest-api_1  |         at me.lucko.luckperms.lib.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[?:?]
luckperms-rest-api_1  |         at me.lucko.luckperms.lib.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[?:?]
luckperms-rest-api_1  |         at me.lucko.luckperms.lib.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[?:?]
luckperms-rest-api_1  |         at me.lucko.luckperms.lib.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[?:?]
luckperms-rest-api_1  |         at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[?:?]
luckperms-rest-api_1  |         at me.lucko.luckperms.lib.hikari.pool.HikariPool.access$100(HikariPool.java:71) ~[?:?]
luckperms-rest-api_1  |         at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726) ~[?:?]
luckperms-rest-api_1  |         at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712) ~[?:?]
luckperms-rest-api_1  |         at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
luckperms-rest-api_1  |         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
luckperms-rest-api_1  |         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
luckperms-rest-api_1  |         at java.lang.Thread.run(Thread.java:833) ~[?:?]
luckperms-rest-api_1  | [12:24:45 WARN]: Messaging service 'sql' not recognised.
luckperms-rest-api_1  | [12:24:45 INFO]: Loading internal permission managers...
luckperms-rest-api_1  | [12:24:45 INFO]: Loading extension: me.lucko.luckperms.extension.rest.RestExtension (luckperms-rest-api-v1.jar)
luckperms-rest-api_1  | [12:24:45 INFO]: [REST] Starting server...
luckperms-rest-api_1  | [12:24:45 INFO]: Logging initialized @11019ms to org.eclipse.jetty.util.log.Slf4jLog
luckperms-rest-api_1  | [12:24:46 INFO]: [REST] Startup complete! Listening on http://localhost:8181
luckperms-rest-api_1  | [12:24:46 INFO]: Performing initial data load...
luckperms-rest-api_1  | java.util.concurrent.CompletionException: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5000ms.
luckperms-rest-api_1  |         at me.lucko.luckperms.common.storage.Storage.lambda$future$1(Storage.java:106)
luckperms-rest-api_1  |         at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
luckperms-rest-api_1  |         at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
luckperms-rest-api_1  |         at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
luckperms-rest-api_1  |         at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
luckperms-rest-api_1  |         at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
luckperms-rest-api_1  |         at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
luckperms-rest-api_1  |         at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
luckperms-rest-api_1  | Caused by: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5000ms.
luckperms-rest-api_1  |         at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696)
luckperms-rest-api_1  |         at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
luckperms-rest-api_1  |         at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
luckperms-rest-api_1  |         at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
luckperms-rest-api_1  |         at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:174)
luckperms-rest-api_1  |         at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.loadAllGroups(SqlStorage.java:503)
luckperms-rest-api_1  |         at me.lucko.luckperms.common.storage.Storage.lambda$loadAllGroups$11(Storage.java:205)
luckperms-rest-api_1  |         at me.lucko.luckperms.common.storage.Storage.lambda$future$1(Storage.java:101)
luckperms-rest-api_1  |         ... 7 more
luckperms-rest-api_1  | Caused by: java.sql.SQLException: Access denied for user 'ungmcraft_lp'@'172.19.0.2' (using password: YES)
luckperms-rest-api_1  |         at me.lucko.luckperms.lib.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
luckperms-rest-api_1  |         at me.lucko.luckperms.lib.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
luckperms-rest-api_1  |         at me.lucko.luckperms.lib.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:833)
luckperms-rest-api_1  |         at me.lucko.luckperms.lib.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453)
luckperms-rest-api_1  |         at me.lucko.luckperms.lib.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
luckperms-rest-api_1  |         at me.lucko.luckperms.lib.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
luckperms-rest-api_1  |         at me.lucko.luckperms.lib.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
luckperms-rest-api_1  |         at me.lucko.luckperms.lib.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
luckperms-rest-api_1  |         at me.lucko.luckperms.lib.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
luckperms-rest-api_1  |         at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
luckperms-rest-api_1  |         at me.lucko.luckperms.lib.hikari.pool.HikariPool.access$100(HikariPool.java:71)
luckperms-rest-api_1  |         at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726)
luckperms-rest-api_1  |         at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712)
luckperms-rest-api_1  |         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
luckperms-rest-api_1  |         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
luckperms-rest-api_1  |         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
luckperms-rest-api_1  |         at java.base/java.lang.Thread.run(Thread.java:833)
`

**Comment by powercasgamer** [comment]
> Caused by: java.sql.SQLException: Access denied for user 'ungmcraft_lp'@'172.19.0.2' (using password: YES)

Have a look at [this](https://luckperms.net/wiki/Storage-system-errors#luckperms-cannot-connect-to-my-mysql-server)
